import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { runCheckSuite } from "./lib/check-runner.mjs";

const bundledNpmCli = join(dirname(process.execPath), "node_modules", "npm", "bin", "npm-cli.js");
const npmCli = process.env.npm_execpath || bundledNpmCli;
const npmCommand = existsSync(npmCli) ? [process.execPath, npmCli] : ["npm"];

const checks = [
  ["check:js", ["node", "scripts/check-js.mjs"]],
  ["check:json", ["node", "scripts/check-json.mjs"]],
  ["check:protected-content", ["node", "scripts/check-protected-content.mjs"]],
  ["check:private-spinner", ["node", "scripts/check-private-spinner.mjs"]],
  ["test:spinner", ["node", "--experimental-strip-types", "--test", "tests/spinner-raffle.test.ts", "tests/spinner-session.test.ts", "tests/spinner-live.test.ts", "tests/bounded-response.test.ts"]],
  ["check:live-spinner-backend", ["node", "scripts/check-live-spinner-backend.mjs"]],
  ["test:live-spinner-backend", ["deno", "test", "--allow-env", "--node-modules-dir=auto", "--import-map=supabase/functions/spinner-live-session/deno.json", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/spinner-live_test.ts", "supabase/functions/_shared/spinner-media_test.ts"]],
  ["check:raffle-public", ["node", "scripts/check-raffle-closed-state.mjs"]],
  ["test:raffle-public", ["node", "--experimental-default-type=module", "--experimental-strip-types", "--test", "apps/web/lib/raffle/public-view_test.ts"]],
  ["test:raffle-latest-winner", ["node", "--experimental-default-type=module", "--experimental-strip-types", "--test", "apps/web/lib/raffle/latest-winner-core.test.mts"]],
  ["test:raffle-leaderboard", [...npmCommand, "--prefix", "apps/web", "run", "test:raffle-leaderboard"]],
  ["raffle SSR boundary contract", [...npmCommand, "--prefix", "apps/web", "run", "check:raffle-server-boundary"]],
  ["raffle SSR boundary tests", [...npmCommand, "--prefix", "apps/web", "run", "test:raffle-server-boundary"]],
  ["test:raffle-leaderboard-edge", ["deno", "test", "--allow-env", "--node-modules-dir=auto", "--config=supabase/functions/get-current-raffle/deno.json", "--lock=supabase/functions/get-current-raffle/deno.lock", "--frozen=true", "supabase/functions/_shared/raffle-core_test.ts", "supabase/functions/_shared/raffle-current_test.ts", "supabase/functions/_shared/raffle-edge_test.ts", "supabase/functions/_shared/raffle-leaderboard_test.ts"]],
  ["check:raffle-disabled-foundation", ["node", "scripts/check-raffle-disabled-foundation.mjs"]],
  ["test:raffle-disabled-foundation", ["deno", "test", "--node-modules-dir=none", "--config=supabase/functions/manage-raffle-claim/deno.json", "--lock=supabase/functions/manage-raffle-claim/deno.lock", "--frozen=true", "supabase/functions/_shared/raffle-claim-boundary_test.ts", "supabase/functions/_shared/raffle-claim_test.ts", "supabase/functions/_shared/raffle-flags_test.ts", "supabase/functions/_shared/raffle-moderator-policy_test.ts", "supabase/functions/_shared/raffle-fulfillment_test.ts", "supabase/functions/_shared/reward-crypto_test.ts", "supabase/functions/_shared/reward-relay-protocol-vector_test.ts", "supabase/functions/_shared/reward-provider-webhook_test.ts"]],
  ["check:reward-relay", ["node", "scripts/check-reward-relay.mjs"]],
  ["check:recruitment-audio-player", ["node", "scripts/check-recruitment-audio-player.mjs"]],
  ["check:content", ["node", "scripts/check-content-guardrails.mjs"]],
  ["check:apac-content", ["node", "scripts/check-apac-content.mjs"]],
  ["check:brand-boundaries", ["node", "scripts/check-brand-boundaries.mjs"]],
  ["check:repository-boundaries", ["node", "scripts/check-repository-boundaries.mjs"]],
  ["check:cross-repository-contracts", ["node", "scripts/check-cross-repository-contract-registry.mjs"]],
  ["test:cross-repository-contracts", ["node", "--test", "scripts/check-cross-repository-contract-registry.test.mjs"]],
  ["check:host-independence", ["node", "scripts/check-host-independence.mjs"]],
  ["check:integration-exposure-catalog", ["node", "scripts/check-integration-exposure-catalog.mjs"]],
  ["check:edge-response-contracts", ["node", "scripts/check-edge-response-contracts.mjs"]],
  ["test:edge-response-contracts", ["node", "scripts/check-edge-response-contracts.mjs", "--self-test"]],
  ["check:legal-privacy-readiness", ["node", "scripts/check-legal-privacy-readiness.mjs"]],
  ["check:shopify-release-safety", ["node", "apps/shopify-theme/scripts/check-release-safety.mjs"]],
  ["check:shopify-launch-readiness", ["node", "scripts/check-shopify-launch-readiness.mjs"]],
  ["check:social", [...npmCommand, "--prefix", "services/social", "run", "check:mochirii-ops"]],
  ["check:code-cleanliness", ["node", "scripts/check-code-cleanliness.mjs"]],
  ["check:github-actions-security", ["node", "scripts/check-github-actions-security.mjs"]],
  ["test:supabase-secret-assignment-scanner", ["node", "--test", "scripts/lib/supabase-secret-assignment-scanner.test.mjs"]],
  ["check:supabase-config", ["node", "scripts/check-supabase-public-config.mjs"]],
  ["check:discord-gallery-ingest", ["node", "scripts/check-discord-gallery-ingest.mjs"]],
  ["test:discord-gallery-ingest-auth", ["deno", "test", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/discord-gallery-ingest-auth_test.ts"]],
  ["check:discord-reaper-parity", ["node", "scripts/check-discord-reaper-parity.mjs"]],
  ["check:discord-event-covers", ["node", "scripts/check-discord-event-covers.mjs"]],
  ["check:reaper-discord-interactions", ["node", "scripts/check-reaper-discord-interactions.mjs"]],
  ["test:photo-day-poll", ["deno", "test", "--allow-env", "--node-modules-dir=auto", "--import-map=supabase/functions/reaper-discord-interactions/deno.json", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/photo-day-polls_test.ts"]],
  ["test:discord-signature", ["deno", "test", "--allow-env", "--node-modules-dir=auto", "--import-map=supabase/functions/reaper-discord-interactions/deno.json", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/discord-signature_test.ts"]],
  ["test:edge-request-security", ["deno", "test", "--allow-env", "--node-modules-dir=auto", "--import-map=supabase/functions/reaper-discord-interactions/deno.json", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/bounded-request-body_test.ts", "supabase/functions/_shared/discord-api_test.ts", "supabase/functions/_shared/outbound-http_test.ts", "supabase/functions/_shared/secret-auth_test.ts"]],
  ["test:reaper-discord-events", ["deno", "test", "--allow-env", "--node-modules-dir=auto", "--import-map=supabase/functions/reaper-discord-interactions/deno.json", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/reaper-discord-events_test.ts"]],
  ["check:reaper-modmail-audit", ["node", "scripts/check-reaper-modmail-audit.mjs"]],
  ["test:reaper-pending-verification", ["deno", "test", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/pending-verification-containment_test.ts"]],
  ["check:vote-reminder", ["node", "scripts/check-vote-reminder.mjs"]],
  ["check:instagram-gallery-publishing", ["node", "scripts/check-instagram-gallery-publishing.mjs"]],
  ["test:instagram-publishing", ["deno", "test", "--node-modules-dir=auto", "--import-map=supabase/functions/publish-instagram-gallery-submission/deno.json", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/instagram-publishing_test.ts"]],
  ["test:instagram-action-confirmation", ["node", "--experimental-default-type=module", "--experimental-strip-types", "--test", "apps/web/lib/gallery/instagram-action-confirmation_test.ts"]],
  ["test:social-publication-copy", ["node", "--experimental-default-type=module", "--experimental-strip-types", "--test", "apps/web/lib/gallery/social-publication-copy.test.mts"]],
  ["check:facebook-page-gallery-publishing", ["node", "scripts/check-facebook-page-gallery-publishing.mjs"]],
  ["test:facebook-page-action-confirmation", ["node", "--experimental-default-type=module", "--experimental-strip-types", "--test", "apps/web/lib/gallery/facebook-action-confirmation_test.ts"]],
  ["test:social-publication-confirmation", ["node", "--experimental-default-type=module", "--experimental-strip-types", "--test", "apps/web/lib/gallery/social-publication-confirmation_test.ts"]],
  ["test:social-publication-request", ["node", "--experimental-default-type=module", "--experimental-strip-types", "--test", "apps/web/lib/gallery/social-publication-request_test.ts"]],
  ["test:social-consent-withdrawal", ["node", "--experimental-default-type=module", "--experimental-strip-types", "--test", "apps/web/lib/gallery/social-consent-withdrawal_test.ts"]],
  ["test:facebook-page-publishing", ["deno", "test", "--node-modules-dir=auto", "--import-map=supabase/functions/publish-facebook-page-gallery-submission/deno.json", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/facebook-page-publishing_test.ts"]],
  ["check:meta-gallery-release-manifest", ["node", "scripts/check-meta-gallery-release-manifest.mjs"]],
  ["test:meta-gallery-security", ["deno", "test", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/meta-graph-security_test.ts", "supabase/functions/_shared/meta-provider-diagnostic_test.ts", "supabase/functions/_shared/social-publication-confirmation_test.ts", "supabase/functions/_shared/social-publication-copy_test.ts", "supabase/functions/_shared/safe-telemetry_test.ts"]],
  ["check:meta-public-readiness", ["node", "scripts/check-meta-public-readiness.mjs"]],
  ["check:member-profiles-and-ranks", ["node", "scripts/check-member-profiles-and-ranks.mjs"]],
  ["check:member-social-links", ["node", "scripts/check-member-social-links.mjs"]],
  ["test:member-social-links", ["node", "--experimental-default-type=module", "--experimental-strip-types", "--test", "apps/web/lib/member-social-links/profile-links-core.test.mts"]],
  ["check:member-workflow-qa", ["node", "scripts/check-member-workflow-qa.mjs"]],
  ["test:member-verification-identity", ["deno", "test", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/member-verification-identity_test.ts"]],
  ["test:supabase-service-role", ["deno", "test", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/supabase-service-role_test.ts"]],
  ["check:multi-provider-auth", ["node", "scripts/check-multi-provider-auth.mjs"]],
  ["check:apple-auth-readiness", ["node", "scripts/check-apple-auth-readiness.mjs"]],
  ["test:auth-provider-brand-asset-bytes", ["node", "--test", "scripts/lib/canonical-checkout-text.test.mjs"]],
  ["check:auth-provider-brand-assets", ["node", "scripts/check-auth-provider-brand-assets.mjs"]],
  ["test:auth-provider-policy", ["node", "--experimental-default-type=module", "--experimental-strip-types", "--test", "apps/web/lib/supabase/auth-provider-policy-core.test.mts"]],
  ["check:auth-provider-state-cleanup", ["node", "scripts/check-auth-provider-state-cleanup.mjs"]],
  ["check:phone-auth-abuse-controls", ["node", "scripts/check-phone-auth-abuse-controls.mjs"]],
  ["test:phone-auth-policy", [...npmCommand, "--prefix", "apps/web", "run", "test:phone-auth-policy"]],
  ["check:mochi-pets-tester-doorway", ["node", "scripts/check-mochi-pets-tester-doorway.mjs"]],
  ["test:mochi-pets-member-verification", ["node", "--experimental-default-type=module", "--experimental-strip-types", "apps/web/lib/mochi-pets/member-verification-core.test.mts"]],
  ["test:mochi-pets-tester-access-policy", ["node", "--experimental-default-type=module", "--experimental-strip-types", "apps/web/lib/mochi-pets/tester-access-policy-core.test.mts"]],
  ["test:mochi-pets-tester-rate-limit", ["node", "--experimental-default-type=module", "--experimental-strip-types", "apps/web/lib/mochi-pets/tester-rate-limit.test.mts"]],
  ["test:mochi-pets-tester-session", ["node", "--experimental-default-type=module", "--experimental-strip-types", "apps/web/lib/mochi-pets/tester-session-core.test.mts"]],
  ["check:mochi-pets-edge-authority", ["node", "scripts/check-mochi-pets-edge-authority.mjs"]],
  ["test:mochi-pets-alpha", ["deno", "test", "--allow-env", "--node-modules-dir=auto", "--import-map=supabase/functions/mochi-pets-unity-auth/deno.json", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/mochi-pets-alpha_test.ts"]],
  ["test:pixelfed-social-sync", ["deno", "test", "--allow-env", "--node-modules-dir=auto", "--import-map=supabase/functions/sync-pixelfed-social-account/deno.json", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/pixelfed-social-sync_test.ts", "supabase/functions/_shared/member-access-policy_test.ts", "supabase/functions/_shared/discord-membership-response_test.ts", "supabase/functions/_shared/social-discord-membership_test.ts"]],
  ["test:member-access-refresh", ["deno", "test", "--allow-env", "--node-modules-dir=auto", "--import-map=supabase/functions/verify-member-access/deno.json", "--lock=deno.lock", "--frozen=true", "supabase/functions/verify-member-access/index_test.ts"]],
  ["check:supabase-edge-types", ["node", "scripts/check-supabase-edge-types.mjs"]],
  ["check:cutover-validators", ["node", "scripts/check-cutover-validator-self-tests.mjs"]],
  ["check:gallery-approved-feed", ["node", "scripts/check-gallery-approved-feed.mjs"]],
  ["test:gallery-approved-feed-client", ["node", "--experimental-default-type=module", "--experimental-strip-types", "--test", "apps/web/lib/gallery/approved-feed_test.ts"]],
  ["test:gallery-browser-state", ["node", "--experimental-default-type=module", "--experimental-strip-types", "--test", "apps/web/lib/gallery/browser-state_test.ts"]],
  ["test:gallery-safe-preview", ["node", "--experimental-default-type=module", "--experimental-strip-types", "--test", "apps/web/lib/gallery/safe-preview_test.ts"]],
  ["test:live-gallery-media-smoke-guard", ["node", "--test", "scripts/lib/live-gallery-media-smoke-guard.test.mjs", "scripts/gallery-lighthouse-local-fixture.test.mjs"]],
  ["test:gallery-thumbnail", ["deno", "test", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/gallery-thumbnail_test.ts"]],
  ["test:gallery-source-image", ["deno", "test", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/gallery-source-image_test.ts"]],
  ["test:gallery-source-decode", ["deno", "test", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/gallery-source-decode_test.ts"]],
  ["test:gallery-preview-attestation", ["deno", "test", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/gallery-preview-attestation_test.ts"]],
  ["test:gallery-moderation-preview", ["node", "--experimental-default-type=module", "--experimental-strip-types", "--test", "apps/web/lib/gallery/moderation-preview-server_test.ts", "apps/web/lib/gallery/moderation-preview-route_test.ts", "apps/web/lib/gallery/moderation-preview-client_test.ts"]],
  ["test:gallery-moderation-boundaries", ["deno", "test", "--node-modules-dir=auto", "--import-map=supabase/functions/list-gallery-review-queue/deno.json", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/gallery-moderation_test.ts", "supabase/functions/_shared/gallery-response-safety_test.ts"]],
  ["test:gallery-discord-ingest", ["deno", "test", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/gallery-discord-ingest_test.ts"]],
  ["test:gallery-public-feed", ["deno", "test", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/gallery-public-feed_test.ts"]],
  ["check:gallery-timestamps", ["node", "scripts/check-gallery-timestamps.mjs"]],
  ["check:media-performance", ["node", "scripts/check-media-performance.mjs"]],
  ["check:app-route-inventory", ["node", "scripts/check-app-route-inventory.mjs"]],
  ["test:app-route-inventory", ["node", "--test", "scripts/lib/app-router-inventory.test.mjs"]],
  ["check:next-route-delivery", ["node", "scripts/check-next-route-delivery.mjs"]],
  ["check:guild-schedule", ["node", "scripts/check-guild-schedule.mjs"]],
  ["check:event-social-schedule-parity", ["node", "scripts/check-event-social-schedule-parity.mjs"]],
  ["check:event-social-content", ["node", "scripts/check-event-social-content.mjs"]],
  ["test:event-social-content", ["node", "--test", "scripts/lib/event-social-content-contract.test.mjs"]],
  ["check:event-social-assets", ["node", "scripts/check-event-social-assets.mjs"]],
  ["test:event-social-assets", ["node", "--test", "scripts/lib/event-social-assets.test.mjs"]],
  ["test:event-social-schedule", ["deno", "test", "--node-modules-dir=auto", "--config=supabase/functions/run-event-social-publication/deno.json", "--lock=supabase/functions/run-event-social-publication/deno.lock", "--frozen=true", "supabase/functions/_shared/event-social-schedule_test.ts", "supabase/functions/_shared/event-social-scheduler-request_test.ts"]],
  ["test:event-social-templates", ["deno", "test", "--node-modules-dir=auto", "--config=supabase/functions/run-event-social-publication/deno.json", "--lock=supabase/functions/run-event-social-publication/deno.lock", "--frozen=true", "supabase/functions/_shared/event-social-templates_test.ts"]],
  ["test:event-social-publishing", ["deno", "test", "--allow-env=EVENT_FACEBOOK_PAGE_PUBLISH_ENABLED,EVENT_INSTAGRAM_PUBLISH_ENABLED,EVENT_DISCORD_PUBLISH_ENABLED,FACEBOOK_PAGE_PUBLISH_ENABLED,INSTAGRAM_PUBLISH_ENABLED", "--node-modules-dir=auto", "--config=supabase/functions/run-event-social-publication/deno.json", "--lock=supabase/functions/run-event-social-publication/deno.lock", "--frozen=true", "supabase/functions/_shared/event-social-publishing_test.ts"]],
  ["test:event-social-reconciliation", ["deno", "test", "--node-modules-dir=auto", "--config=supabase/functions/resolve-event-social-publication-reconciliation/deno.json", "--lock=supabase/functions/resolve-event-social-publication-reconciliation/deno.lock", "--frozen=true", "supabase/functions/_shared/event-social-reconciliation_test.ts"]],
  ["test:event-social-db-guard", ["node", "--test", "scripts/lib/run-event-social-pgtap.test.mjs"]],
  ["check:home-celebration-splash", ["node", "scripts/check-home-celebration-splash.mjs"]],
  ["check:header-auth-loading", ["node", "scripts/check-header-auth-loading.mjs"]],
  ["test:header-auth-loader", ["deno", "test", "--lock=deno.lock", "--frozen=true", "apps/web/components/site-header/deferred-task_test.ts"]],
  ["check:events-page-schedule-sync", ["node", "scripts/check-events-page-schedule-sync.mjs"]],
  ["check:observability-metadata-smoke", ["node", "scripts/check-observability-metadata-smoke.mjs"]],
  ["check:web-runtime-performance", ["node", "scripts/check-web-runtime-performance.mjs"]],
  ["test:web-runtime-performance", [...npmCommand, "--prefix", "apps/web", "run", "test:web-runtime-performance"]],
  ["test:supabase-migration-list", ["node", "scripts/test-supabase-migration-list.mjs"]],
  ["test:supabase-local-preview-contract", ["node", "scripts/check-supabase-local-preview.mjs"]],
  ["check:full-stack-release-evidence", ["node", "scripts/check-full-stack-release-evidence.mjs"]],
  ["check:csp-inline-hardening", ["node", "scripts/check-csp-inline-hardening.mjs"]],
  ["check:accessibility-route-matrix", ["node", "scripts/check-accessibility-route-matrix.mjs"]],
  ["check:pixelfed-oidc-spike", ["node", "scripts/check-pixelfed-oidc-spike.mjs"]],
  ["check:pixelfed-first-login-readiness", ["node", "scripts/check-pixelfed-first-login-readiness.mjs"]],
  ["test:social-oauth-consent", ["node", "--experimental-default-type=module", "--experimental-strip-types", "--test", "apps/web/lib/oauth/approved-social-redirect.test.mts", "apps/web/lib/oauth/authorization-decision-core.test.mts", "apps/web/lib/oauth/authorization-load-queue.test.mts", "apps/web/lib/oauth/consent-login-url.test.mts", "apps/web/lib/oauth/prior-consent-redirect.test.mts", "apps/web/lib/supabase/profile-verification-time.test.mts", "scripts/lib/runtime-diagnostic-redaction.test.mjs"]],
  ["check:shop-brand", ["node", "scripts/check-shop-brand-guardrails.mjs"]],
  ["check:public-guild-brand", ["node", "scripts/check-public-guild-brand.mjs"]],
  ["check:public-guild-copy", ["node", "scripts/check-public-guild-copy.mjs"]],
  ["check:public-disclosure-policy", ["node", "scripts/check-public-disclosure-policy.mjs"]],
  ["test:public-guild-copy-policy", ["node", "--test", "scripts/lib/public-guild-copy-policy.test.mjs"]],
  ["check:site-navigation", ["node", "scripts/check-site-navigation.mjs"]],
  ["check:official-guild-profiles", ["node", "scripts/check-official-guild-profiles.mjs", "--require-meta-marks"]],
  ["check:supabase-security-performance", ["node", "scripts/check-supabase-security-performance.mjs"]],
  ["check:security-hardening", ["node", "scripts/check-security-hardening.mjs"]],
  ["check:spotlight-poll", ["node", "scripts/check-spotlight-poll.mjs"]],
  ["check:refs", ["node", "scripts/check-refs.mjs"]],
  ["test:reviewed-vendor-assets", ["node", "--test", "scripts/lib/reviewed-vendor-assets.test.mjs"]],
  ["check:assets", ["node", "scripts/check-assets.mjs"]],
  ["check:universal-lightbox", ["node", "scripts/check-universal-lightbox.mjs"]],
  ["check:universal-hero-spacing", ["node", "scripts/check-universal-hero-spacing.mjs"]],
];

if (!runCheckSuite(checks)) {
  console.error("\nValidation failed.");
  process.exit(1);
}

console.log("\nAll validation checks completed.");
