import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { runCheckSuite } from "./lib/check-runner.mjs";

const bundledNpmCli = join(dirname(process.execPath), "node_modules", "npm", "bin", "npm-cli.js");
const npmCli = process.env.npm_execpath || bundledNpmCli;
const npmCommand = existsSync(npmCli) ? [process.execPath, npmCli] : ["npm"];

const checks = [
  ["check:js", ["node", "scripts/check-js.mjs"]],
  ["check:json", ["node", "scripts/check-json.mjs"]],
  ["check:protected-content", ["node", "scripts/check-protected-content.mjs"]],
  ["check:private-spinner", ["node", "scripts/check-private-spinner.mjs"]],
  ["test:spinner", ["node", "--experimental-strip-types", "--test", "tests/spinner-raffle.test.ts", "tests/spinner-session.test.ts", "tests/spinner-live.test.ts", "tests/bounded-response.test.ts"]],
  ["check:live-spinner-backend", ["node", "scripts/check-live-spinner-backend.mjs"]],
  ["test:live-spinner-backend", ["deno", "test", "--allow-env", "--node-modules-dir=auto", "--import-map=supabase/functions/spinner-live-session/deno.json", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/spinner-live_test.ts", "supabase/functions/_shared/spinner-media_test.ts"]],
  ["check:raffle-public", ["node", "scripts/check-raffle-closed-state.mjs"]],
  ["test:raffle-public", ["node", "--experimental-default-type=module", "--experimental-strip-types", "--test", "apps/web/lib/raffle/public-view_test.ts"]],
  ["test:raffle-latest-winner", ["node", "--experimental-default-type=module", "--experimental-strip-types", "--test", "apps/web/lib/raffle/latest-winner-core.test.mts"]],
  ["check:recruitment-audio-player", ["node", "scripts/check-recruitment-audio-player.mjs"]],
  ["check:content", ["node", "scripts/check-content-guardrails.mjs"]],
  ["check:apac-content", ["node", "scripts/check-apac-content.mjs"]],
  ["check:brand-boundaries", ["node", "scripts/check-brand-boundaries.mjs"]],
  ["check:repository-boundaries", ["node", "scripts/check-repository-boundaries.mjs"]],
  ["check:cross-repository-contracts", ["node", "scripts/check-cross-repository-contract-registry.mjs"]],
  ["test:cross-repository-contracts", ["node", "--test", "scripts/check-cross-repository-contract-registry.test.mjs"]],
  ["check:host-independence", ["node", "scripts/check-host-independence.mjs"]],
  ["check:shopify-release-safety", ["node", "apps/shopify-theme/scripts/check-release-safety.mjs"]],
  ["check:social", [...npmCommand, "--prefix", "services/social", "run", "check:mochirii-ops"]],
  ["check:code-cleanliness", ["node", "scripts/check-code-cleanliness.mjs"]],
  ["check:github-actions-security", ["node", "scripts/check-github-actions-security.mjs"]],
  ["check:supabase-config", ["node", "scripts/check-supabase-public-config.mjs"]],
  ["check:discord-gallery-ingest", ["node", "scripts/check-discord-gallery-ingest.mjs"]],
  ["check:discord-reaper-parity", ["node", "scripts/check-discord-reaper-parity.mjs"]],
  ["check:discord-event-covers", ["node", "scripts/check-discord-event-covers.mjs"]],
  ["check:reaper-discord-interactions", ["node", "scripts/check-reaper-discord-interactions.mjs"]],
  ["test:photo-day-poll", ["deno", "test", "--allow-env", "--node-modules-dir=auto", "--import-map=supabase/functions/reaper-discord-interactions/deno.json", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/photo-day-polls_test.ts"]],
  ["test:discord-signature", ["deno", "test", "--allow-env", "--node-modules-dir=auto", "--import-map=supabase/functions/reaper-discord-interactions/deno.json", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/discord-signature_test.ts"]],
  ["test:reaper-discord-events", ["deno", "test", "--allow-env", "--node-modules-dir=auto", "--import-map=supabase/functions/reaper-discord-interactions/deno.json", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/reaper-discord-events_test.ts"]],
  ["check:reaper-modmail-audit", ["node", "scripts/check-reaper-modmail-audit.mjs"]],
  ["test:reaper-pending-verification", ["deno", "test", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/pending-verification-containment_test.ts"]],
  ["check:vote-reminder", ["node", "scripts/check-vote-reminder.mjs"]],
  ["check:instagram-gallery-publishing", ["node", "scripts/check-instagram-gallery-publishing.mjs"]],
  ["check:member-profiles-and-ranks", ["node", "scripts/check-member-profiles-and-ranks.mjs"]],
  ["check:member-social-links", ["node", "scripts/check-member-social-links.mjs"]],
  ["test:member-social-links", ["node", "--experimental-default-type=module", "--experimental-strip-types", "--test", "apps/web/lib/member-social-links/profile-links-core.test.mts"]],
  ["check:member-workflow-qa", ["node", "scripts/check-member-workflow-qa.mjs"]],
  ["test:member-verification-identity", ["deno", "test", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/member-verification-identity_test.ts"]],
  ["test:supabase-service-role", ["deno", "test", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/supabase-service-role_test.ts"]],
  ["check:multi-provider-auth", ["node", "scripts/check-multi-provider-auth.mjs"]],
  ["check:apple-auth-readiness", ["node", "scripts/check-apple-auth-readiness.mjs"]],
  ["check:auth-provider-state-cleanup", ["node", "scripts/check-auth-provider-state-cleanup.mjs"]],
  ["check:mochi-pets-tester-doorway", ["node", "scripts/check-mochi-pets-tester-doorway.mjs"]],
  ["test:mochi-pets-member-verification", ["node", "--experimental-default-type=module", "--experimental-strip-types", "apps/web/lib/mochi-pets/member-verification-core.test.mts"]],
  ["test:mochi-pets-tester-access-policy", ["node", "--experimental-default-type=module", "--experimental-strip-types", "apps/web/lib/mochi-pets/tester-access-policy-core.test.mts"]],
  ["test:mochi-pets-tester-rate-limit", ["node", "--experimental-default-type=module", "--experimental-strip-types", "apps/web/lib/mochi-pets/tester-rate-limit.test.mts"]],
  ["test:mochi-pets-tester-session", ["node", "--experimental-default-type=module", "--experimental-strip-types", "apps/web/lib/mochi-pets/tester-session-core.test.mts"]],
  ["check:mochi-pets-edge-authority", ["node", "scripts/check-mochi-pets-edge-authority.mjs"]],
  ["test:mochi-pets-alpha", ["deno", "test", "--allow-env", "--node-modules-dir=auto", "--import-map=supabase/functions/mochi-pets-unity-auth/deno.json", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/mochi-pets-alpha_test.ts"]],
  ["test:pixelfed-social-sync", ["deno", "test", "--allow-env", "--node-modules-dir=auto", "--import-map=supabase/functions/sync-pixelfed-social-account/deno.json", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/pixelfed-social-sync_test.ts", "supabase/functions/_shared/member-access-policy_test.ts"]],
  ["test:member-access-refresh", ["deno", "test", "--allow-env", "--node-modules-dir=auto", "--import-map=supabase/functions/verify-member-access/deno.json", "--lock=deno.lock", "--frozen=true", "supabase/functions/verify-member-access/index_test.ts"]],
  ["check:supabase-edge-types", ["node", "scripts/check-supabase-edge-types.mjs"]],
  ["check:cutover-validators", ["node", "scripts/check-cutover-validator-self-tests.mjs"]],
  ["check:gallery-approved-feed", ["node", "scripts/check-gallery-approved-feed.mjs"]],
  ["test:live-gallery-media-smoke-guard", ["node", "--test", "scripts/lib/live-gallery-media-smoke-guard.test.mjs"]],
  ["test:gallery-thumbnail", ["deno", "test", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/gallery-thumbnail_test.ts"]],
  ["check:gallery-timestamps", ["node", "scripts/check-gallery-timestamps.mjs"]],
  ["check:media-performance", ["node", "scripts/check-media-performance.mjs"]],
  ["check:next-route-delivery", ["node", "scripts/check-next-route-delivery.mjs"]],
  ["check:guild-schedule", ["node", "scripts/check-guild-schedule.mjs"]],
  ["check:home-celebration-splash", ["node", "scripts/check-home-celebration-splash.mjs"]],
  ["check:header-auth-loading", ["node", "scripts/check-header-auth-loading.mjs"]],
  ["test:header-auth-loader", ["deno", "test", "--lock=deno.lock", "--frozen=true", "apps/web/components/site-header/deferred-task_test.ts"]],
  ["check:events-page-schedule-sync", ["node", "scripts/check-events-page-schedule-sync.mjs"]],
  ["check:observability-metadata-smoke", ["node", "scripts/check-observability-metadata-smoke.mjs"]],
  ["check:web-runtime-performance", ["node", "scripts/check-web-runtime-performance.mjs"]],
  ["test:web-runtime-performance", [...npmCommand, "--prefix", "apps/web", "run", "test:web-runtime-performance"]],
  ["test:supabase-migration-list", ["node", "scripts/test-supabase-migration-list.mjs"]],
  ["check:full-stack-release-evidence", ["node", "scripts/check-full-stack-release-evidence.mjs"]],
  ["check:csp-inline-hardening", ["node", "scripts/check-csp-inline-hardening.mjs"]],
  ["check:accessibility-route-matrix", ["node", "scripts/check-accessibility-route-matrix.mjs"]],
  ["check:pixelfed-oidc-spike", ["node", "scripts/check-pixelfed-oidc-spike.mjs"]],
  ["check:pixelfed-first-login-readiness", ["node", "scripts/check-pixelfed-first-login-readiness.mjs"]],
  ["test:social-oauth-consent", ["node", "--experimental-default-type=module", "--experimental-strip-types", "--test", "apps/web/lib/oauth/approved-social-redirect.test.mts", "apps/web/lib/oauth/authorization-load-queue.test.mts", "apps/web/lib/oauth/consent-login-url.test.mts", "apps/web/lib/oauth/prior-consent-redirect.test.mts"]],
  ["check:shop-brand", ["node", "scripts/check-shop-brand-guardrails.mjs"]],
  ["check:public-guild-brand", ["node", "scripts/check-public-guild-brand.mjs"]],
  ["check:site-navigation", ["node", "scripts/check-site-navigation.mjs"]],
  ["check:supabase-security-performance", ["node", "scripts/check-supabase-security-performance.mjs"]],
  ["check:security-hardening", ["node", "scripts/check-security-hardening.mjs"]],
  ["check:spotlight-poll", ["node", "scripts/check-spotlight-poll.mjs"]],
  ["check:refs", ["node", "scripts/check-refs.mjs"]],
  ["check:assets", ["node", "scripts/check-assets.mjs"]],
  ["check:universal-lightbox", ["node", "scripts/check-universal-lightbox.mjs"]],
  ["check:universal-hero-spacing", ["node", "scripts/check-universal-hero-spacing.mjs"]],
];

if (!runCheckSuite(checks)) {
  console.error("\nValidation failed.");
  process.exit(1);
}

console.log("\nAll validation checks completed.");
